// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_highscoreRespawn = new UnifiedLeaderboard("HighscoreRespawn",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Telemetry_HSRespawns"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-qmC67kcEAIQAA"
#else
            "HighscoreRespawn"
#endif
            );

        public static UnifiedLeaderboard HighscoreRespawn
        {
            get { return s_highscoreRespawn; }
        }

        private static readonly UnifiedLeaderboard s_highscoreNoRespawns = new UnifiedLeaderboard("HighscoreNoRespawns",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Telemetry_HsNoRespawns"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIqmC67kcEAIQAQ"
#else
            "HighscoreNoRespawns"
#endif
            );

        public static UnifiedLeaderboard HighscoreNoRespawns
        {
            get { return s_highscoreNoRespawns; }
        }

        private static readonly UnifiedLeaderboard s_planetsReached = new UnifiedLeaderboard("PlanetsReached",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "Telemetry_PlanetsReached"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI-qmC67kcEAIQAg"
#else
            "PlanetsReached"
#endif
            );

        public static UnifiedLeaderboard PlanetsReached
        {
            get { return s_planetsReached; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "HighscoreRespawn", s_highscoreRespawn },
            { "HighscoreNoRespawns", s_highscoreNoRespawns },
            { "PlanetsReached", s_planetsReached },
        };
    }
}
